# 0. Load imports 

In [1]:
## imports
import pandas as pd
import numpy as np
import re

## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")

# 1. Questions: list comprehension

- In class example, why did we need the "courses" at the beginning of the list iteration
- How did the join syntax work in the example where we paste together offenses from same ward

In [2]:
## toy example

### pool of courses
all_courses = ["QSS20", "QSS17", "GOV10", "GOV4", "CSC1"]


## 1.1 Application 1: filtering to a smaller list

When we might use: have a lot of columns in a dataframe; want to filter to a smaller set using some pattern

In [3]:
### pull out ones that contain GOV in the string
gov_c = [course for course in all_courses if "GOV" in course]
gov_c # result

['GOV10', 'GOV4']

In [4]:
### showing that the "course" is just a placeholder/
### arbitrary interator
gov_c_alt = [x for x in all_courses if "GOV" in x]

gov_c == gov_c_alt

True

## 1.2 Application two: keep all objects in the list but do some transformation

In [5]:
all_courses

## strip the numbers from the course names
courses_prefix = [x[:3] for x in all_courses]
courses_prefix # could then find unique elements


['QSS20', 'QSS17', 'GOV10', 'GOV4', 'CSC1']

['QSS', 'QSS', 'GOV', 'GOV', 'CSC']

In [6]:
# Join all together example
" #:(# ".join(courses_prefix)

'QSS #:(# QSS #:(# GOV #:(# GOV #:(# CSC'

#### Your turn: Using original list, add "dartmouth_" prefix to the course name

In [21]:
[ "dartmouth_" + x for x in all_courses ]

['dartmouth_QSS20',
 'dartmouth_QSS17',
 'dartmouth_GOV10',
 'dartmouth_GOV4',
 'dartmouth_CSC1']

## 1.3 Subsetting columns

Use list comprehension to filter to columns with id in the string. Then, create a new dataframe called df1 that contains only column heads with "id"

In [7]:
id_cols = [col for col in df.columns if "ID" in col]
id_cols

## Then, filter the data
df[id_cols]

['BID', 'OBJECTID', 'OCTO_RECORD_ID']

BID   OBJECTID  OCTO_RECORD_ID
0                  NaN  595556840             NaN
1             DOWNTOWN  595560645             NaN
2                  NaN  595560647             NaN
3      GOLDEN TRIANGLE  595560654             NaN
4                  NaN  595560828             NaN
...                ...        ...             ...
27926              NaN  596085252             NaN
27927              NaN  596085253             NaN
27928              NaN  596085258             NaN
27929         DOWNTOWN  596085259             NaN
27930              NaN  596086062             NaN

[27931 rows x 3 columns]

## 1.4 Comprehension for numbers

Here we compare two ways of creating a list of even numbers.

In [8]:
num_list = np.arange(10000)
num_list

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [9]:
%%time
even_nums = [i for i in num_list if (i % 2) == 0]

CPU times: user 5.77 ms, sys: 330 µs, total: 6.1 ms
Wall time: 7.24 ms


In [10]:
%%time
num_list[~(num_list % 2).astype(bool)]

CPU times: user 1.51 ms, sys: 1.54 ms, total: 3.05 ms
Wall time: 2.24 ms


array([   0,    2,    4, ..., 9994, 9996, 9998])

In [16]:
num_list[ ~(num_list % 2).astype(bool) ]

array([   0,    2,    4, ..., 9994, 9996, 9998])

#### Your turn: Extract all numbers in num_list that end in 7

In [26]:
%%time
end_seven = [i for i in num_list if (i%10) == 7]
# end_seven

CPU times: user 10 ms, sys: 433 µs, total: 10.5 ms
Wall time: 11.6 ms


In [27]:
%%time
end_seven = [x for x in num_list if str(x)[-1] == "7"]
# end_seven

CPU times: user 13.7 ms, sys: 4.29 ms, total: 18 ms
Wall time: 19.4 ms


In [29]:
%%time
aa = num_list[num_list % 10 == 7]

CPU times: user 840 µs, sys: 158 µs, total: 998 µs
Wall time: 858 µs


#### Your turn: Divide each number  in num_list by 2

In [37]:
divide_two = [int( i/2 ) for i in num_list]
divide_two

[0,
 0,
 1,
 1,
 2,
 2,
 3,
 3,
 4,
 4,
 5,
 5,
 6,
 6,
 7,
 7,
 8,
 8,
 9,
 9,
 10,
 10,
 11,
 11,
 12,
 12,
 13,
 13,
 14,
 14,
 15,
 15,
 16,
 16,
 17,
 17,
 18,
 18,
 19,
 19,
 20,
 20,
 21,
 21,
 22,
 22,
 23,
 23,
 24,
 24,
 25,
 25,
 26,
 26,
 27,
 27,
 28,
 28,
 29,
 29,
 30,
 30,
 31,
 31,
 32,
 32,
 33,
 33,
 34,
 34,
 35,
 35,
 36,
 36,
 37,
 37,
 38,
 38,
 39,
 39,
 40,
 40,
 41,
 41,
 42,
 42,
 43,
 43,
 44,
 44,
 45,
 45,
 46,
 46,
 47,
 47,
 48,
 48,
 49,
 49,
 50,
 50,
 51,
 51,
 52,
 52,
 53,
 53,
 54,
 54,
 55,
 55,
 56,
 56,
 57,
 57,
 58,
 58,
 59,
 59,
 60,
 60,
 61,
 61,
 62,
 62,
 63,
 63,
 64,
 64,
 65,
 65,
 66,
 66,
 67,
 67,
 68,
 68,
 69,
 69,
 70,
 70,
 71,
 71,
 72,
 72,
 73,
 73,
 74,
 74,
 75,
 75,
 76,
 76,
 77,
 77,
 78,
 78,
 79,
 79,
 80,
 80,
 81,
 81,
 82,
 82,
 83,
 83,
 84,
 84,
 85,
 85,
 86,
 86,
 87,
 87,
 88,
 88,
 89,
 89,
 90,
 90,
 91,
 91,
 92,
 92,
 93,
 93,
 94,
 94,
 95,
 95,
 96,
 96,
 97,
 97,
 98,
 98,
 99,
 99,
 100,
 100,
 101,
 1

In [39]:
num_list / 2 

[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5,
 10.0,
 10.5,
 11.0,
 11.5,
 12.0,
 12.5,
 13.0,
 13.5,
 14.0,
 14.5,
 15.0,
 15.5,
 16.0,
 16.5,
 17.0,
 17.5,
 18.0,
 18.5,
 19.0,
 19.5,
 20.0,
 20.5,
 21.0,
 21.5,
 22.0,
 22.5,
 23.0,
 23.5,
 24.0,
 24.5,
 25.0,
 25.5,
 26.0,
 26.5,
 27.0,
 27.5,
 28.0,
 28.5,
 29.0,
 29.5,
 30.0,
 30.5,
 31.0,
 31.5,
 32.0,
 32.5,
 33.0,
 33.5,
 34.0,
 34.5,
 35.0,
 35.5,
 36.0,
 36.5,
 37.0,
 37.5,
 38.0,
 38.5,
 39.0,
 39.5,
 40.0,
 40.5,
 41.0,
 41.5,
 42.0,
 42.5,
 43.0,
 43.5,
 44.0,
 44.5,
 45.0,
 45.5,
 46.0,
 46.5,
 47.0,
 47.5,
 48.0,
 48.5,
 49.0,
 49.5,
 50.0,
 50.5,
 51.0,
 51.5,
 52.0,
 52.5,
 53.0,
 53.5,
 54.0,
 54.5,
 55.0,
 55.5,
 56.0,
 56.5,
 57.0,
 57.5,
 58.0,
 58.5,
 59.0,
 59.5,
 60.0,
 60.5,
 61.0,
 61.5,
 62.0,
 62.5,
 63.0,
 63.5,
 64.0,
 64.5,
 65.0,
 65.5,
 66.0,
 66.5,
 67.0,
 67.5,
 68.0,
 68.5,
 69.0,
 69.5,
 70.0,
 70.5,
 71.0,
 71.5,
 72.0,
 72.5

# 2. Questions: lambda functions

Two questions:

- General syntax (see here for a reference: https://www.w3schools.com/python/python_lambda.asp 
- How they work in the context of aggregations

How is a lambda function different from a "normal" user-defined function (that has the syntax def func_name(arg): etc?

- Operates similarly to normal user-defined functions in that it can take any # of arguments
- Operates differently in that it's an "anonymous" function or a function that we don't explicitly name/save in memory

In [17]:
def f1(x,y):
    return x+y

f2 = lambda x, y: x+y

f1(2,1)
f2(2,1)

3

3

In [18]:
f1("hi", " world")

'hi world'

## 2.1 General syntax for lambda functions

In [36]:
### two pools of courses
socsci = ["QSS20", "QSS17", "GOV10"]
natsci = ["BIO2", "PHYS3"]


## generalize some of the steps
## above into a two-arg function
## that takes the course prefix
## and a list of all courses
def filter_courses(prefix, all_courses):
    rel_courses = [c for c in all_courses if prefix in c]
    return(rel_courses)

### a few applications 
filter_courses(prefix = "QSS", all_courses = socsci)
filter_courses(prefix = "QSS", all_courses = natsci)
filter_courses(prefix = "BIO", all_courses = natsci)

In [ ]:
## what's the lambda function version of this
filter_courses_v2 = lambda prefix, all_courses: [c for c in all_courses if prefix in c]
filter_courses_v2(prefix = "BIO", all_courses = natsci)


## 2.2 using alongside agg

In [50]:
## use lambda to find modal block in a ward- multiple ways

### way 1: subsetting agg syntex
df.groupby("WARD")["BLOCK"].agg(lambda x: x.mode())

### way 2: dictionary agg syntax
df.groupby("WARD").agg({"BLOCK": lambda x: x.mode()})


WARD
1           3100 - 3299 BLOCK OF 14TH STREET NW
2    1300 - 1699 BLOCK OF CONNECTICUT AVENUE NW
3      5300 - 5399 BLOCK OF WISCONSIN AVENUE NW
4          100 - 199 BLOCK OF CARROLL STREET NW
5     900 - 999 BLOCK OF RHODE ISLAND AVENUE NE
6                600 - 699 BLOCK OF H STREET NE
7         934 - 1099 BLOCK OF EASTERN AVENUE NE
8        2300 - 2399 BLOCK OF GOOD HOPE ROAD SE
Name: BLOCK, dtype: object

BLOCK
WARD                                            
1            3100 - 3299 BLOCK OF 14TH STREET NW
2     1300 - 1699 BLOCK OF CONNECTICUT AVENUE NW
3       5300 - 5399 BLOCK OF WISCONSIN AVENUE NW
4           100 - 199 BLOCK OF CARROLL STREET NW
5      900 - 999 BLOCK OF RHODE ISLAND AVENUE NE
6                 600 - 699 BLOCK OF H STREET NE
7          934 - 1099 BLOCK OF EASTERN AVENUE NE
8         2300 - 2399 BLOCK OF GOOD HOPE ROAD SE

#### Your turn: Group by WARD and get the mean and standard deviation (std) of X and Y

In [40]:
df.groupby("WARD").agg({
    "X" : ["mean", "std"],
    "Y" : ["mean", "std"],
})

X                    Y          
           mean       std       mean       std
WARD                                          
1    -77.031256  0.007200  38.924716  0.006417
2    -77.038959  0.014106  38.905941  0.005360
3    -77.075320  0.013408  38.941557  0.013887
4    -77.024905  0.011813  38.957674  0.013923
5    -76.989451  0.014957  38.920249  0.012766
6    -77.001175  0.011302  38.893112  0.010021
7    -76.947402  0.018753  38.888669  0.012504
8    -76.988986  0.012791  38.850526  0.015775

In [43]:
df.groupby("WARD")[["X", "Y"]].agg(["mean", "std"])

X                    Y          
           mean       std       mean       std
WARD                                          
1    -77.031256  0.007200  38.924716  0.006417
2    -77.038959  0.014106  38.905941  0.005360
3    -77.075320  0.013408  38.941557  0.013887
4    -77.024905  0.011813  38.957674  0.013923
5    -76.989451  0.014957  38.920249  0.012766
6    -77.001175  0.011302  38.893112  0.010021
7    -76.947402  0.018753  38.888669  0.012504
8    -76.988986  0.012791  38.850526  0.015775